import Head from 'next/head'
import CarForm from '../Components/CarForm'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/myicon.ico" />
      </Head>
      {/* Form displayed */}
      <CarForm/>

      <footer className={styles.footer}>
         <b> Trying my hands on Memory Databases </b>
      </footer>
    </div>
  )
}
